### ISSUE TITLE
Class 'Adamgoose\AnnotationsServiceProvider' not found

### ISSUE THREAD

**Issue by jonathanpmartins** [adamgoose/laravel-annotations#2]
I don't know why, but when I composer update, the `AnnotationsServiceProvider` file don't download correctly. In the github repository I can see the file, but if I look thought the vendors directory the file is not there.

If I do `php artisan` i get this issue:

Error Output: PHP Fatal error:  Class 'Adamgoose\AnnotationsServiceProvider' not found in app/Providers/AnnotationsServiceProvider.php on line 5.

In line 5 I have: `use Adamgoose\AnnotationsServiceProvider as ServiceProvider;` ...even with a backslash in front `use \Adamgoose\AnnotationsServiceProvider as ServiceProvider;` it don't work, the file is not there.

I try to, unistall, install, remove all vendors files manually, clean my composer cache, but even that don't download the complete package correctly.

I miss the `console` directory on the vendors folder too.

Is this a problem with Composer? or Packegist?

**Comment by jonathanpmartins** [comment]
When I put the files manually in the vendors folder, all systems work fine!

**Comment by adamgoose** [comment]
How strange! Thanks for the info... Think you could remove the vendor directly and re-run composer? I'm thinking it was a fluke...

**Comment by jonathanpmartins** [comment]
Unfortunately I re-run composer like you said and nothing different happened. Composer continue missing 4 files:

    AnnotationFinder.php
    AnnotationsServiceProvider.php
    Console/EventScanCommand.php
    Console/RouteScanCommand.php

**Comment by adamgoose** [comment]
That's insane... Put the files in manually for now, and I'll give it a look
tomorrow.

On Wednesday, January 7, 2015, Jonathan Martins <notifications@github.com>
wrote:

> Unfortunately I re-run composer like you said and nothing different
> happened. Composer continue missing 4 files:
>
> AnnotationFinder.php
> AnnotationsServiceProvider.php
> Console/EventScanCommand.php
> Console/RouteScanCommand.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamgoose/laravel-annotations/issues/2#issuecomment-69133084>
> .
>


-- 
--
Adam Engebretson
*dannenga., LLC*
205 Park Central E.
#519
Springfield, MO 65806
612-567-2326

**Comment by jonathanpmartins** [comment]
Ohhh, I guess i'm getting the master branch, not the development one. Trying this I get the right branch.

    "require": {
        "adamgoose/laravel-annotations": "~5.0@dev"
    }

**Comment by adamgoose** [comment]
Let me push to master now...

On Wednesday, January 7, 2015, Jonathan Martins <notifications@github.com>
wrote:

> Ohhh, I guess i'm getting the master branch, not the development one.
> Trying this I get the right branch.
>
> "require": {
>     "adamgoose/laravel-annotations": "~5.0@dev"
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adamgoose/laravel-annotations/issues/2#issuecomment-69133597>
> .
>


-- 
--
Adam Engebretson
*dannenga., LLC*
205 Park Central E.
#519
Springfield, MO 65806
612-567-2326

**Comment by adamgoose** [comment]
Okay @jonathanpmartins, give it a go now. `~5.0@dev` should now pull the latest.

**Comment by jonathanpmartins** [comment]
Thank you very much. I appreciate the attention. I think this issue can be closed!

`"adamgoose/laravel-annotations": "~5.0"` is working now too...
